### ISSUE TITLE
Idea: get_calibration_range?

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#40] opened 2020-05-19 15:53 UTC
How about a function within each model called get_calibration_range() that returns some statement about what kinds of samples should be used within that model?

**Comment by kaylai** [comment] 2020-05-21 21:24
Adding in Simon's comment from a similar issue:

At the moment the calibration checks are 'hard coded' for each model, there's no reporting for the user anywhere of what the calibration limits are. This also means that the warnings will only tell you that you are outside a calibration range, but won't specify what it is...

e.g. the warning code produces this warning:
"Pressure is outside the calibration range of the CO2 Fugacity Model. Temperature is outside the calibration range of the CO2 Fugacity Model. Pressure is outside the calibration range of the H2O Fugacity Model. Temperature is outside the calibration range of the H2O Fugacity Model. "

This can be fixed by creating some kind of structure for storing the calibration limits, and then making the code check these. This will (potentially) limit the complexity of the possible checks, but will be much more useful for the user!

**Comment by PennyWieser** [comment] 2020-05-26 19:40
@simonwmatthews @kaylai Sorry i'm still catching up as to what has been done -is this check currently for the EOS and fugacity model and things - do you also have a structure of all the PT ranges for the different solubility models? Or do you want the ones i've compiled  for the PT plot? 
![PT Ranges CO2 and mixed CO2-H2O](https://user-images.githubusercontent.com/65668673/82943142-0ae3d880-9f91-11ea-943c-dc085c34ff0c.png)

![image](https://user-images.githubusercontent.com/65668673/82943118-00294380-9f91-11ea-89e1-9ab9439747c0.png)

**Comment by PennyWieser** [comment] 2020-05-26 19:46
Also, @simonwmatthews where were you at with compositional checks before I joined in so I don't duplicate your stuff. Do you just want me to send a list of specific things that should return error messages for each model (e.g., your MgO is out of the published range 6-8 wt%  for Iacono etc.?). Do you think its maybe worth taking the element data from the input file and plotting it onto of the TAS plot that will be in the manuscript? Or still providing a separate Jupyter notebook where people can plot their samples in compositional space to really look into where they lie with respect to the calibration datasets rather than confusing the manuscript with it.

**Comment by kaylai** [comment] 2020-05-26 21:36
I personally haven't gathered any data for the compositional calibration ranges. I have only grabbed P-T calibration ranges for MagmaSat and MooreWater and have implemented those.

Any time a model calculation is called, a calibration check is also performed. This checks that the input parameters are within the calibrated P-T ranges for the fugacity model applied, activity model applied, and for the solubility model applied. This happens in one call. Composition checks are not implemented at all.

**Comment by simonwmatthews** [comment] 2020-05-27 07:49
My plan for this is to totally change how the calibration checks are performed. I've worked out how best to do this, but it will take me a little while to implement (days, not weeks). Essentially, there will be new python 'objects' that describe a logic statement, or potentially a complex logic statement with many variables. This object will be able to check whether the parameters fulfil the logic statement, but will also be able to generate a nice string to explain what has gone wrong! This is overkill for T and P, but will probably be necessary for composition. Most of these objects will be very generic, and very straightforward to use, but by setting it up like this it will give us much more power in defining more complex criteria.

Once it is implemented, it will be very easy to define calibration ranges for each model, and how they are defined will be flexible too. For example, if there's a complex region of composition space for which the model is valid, it will be possible to define this, rather than just saying individual parameters have to be between certain values. You will also be able to query what the calibration ranges are (and have a readable string returned to you!). If the calculation falls outside the calibrated ranges, it will be able to tell you how it was outside them.

I was also thinking that we could define two levels of calibration-range checking... The first would be what the model is expected to be able to deal with, i.e. exactly what the authors state (or intend). The second would be the range of actual data, potentially including gaps as Penny was describing with the Eguchi model experiments. I think this would be a good balance between faithfully reproducing the intention of the models, and providing people with the power to really focus on in the reliability of different models. Does that sound useful? 

I've not done any work on compositional checks so far. I think the most efficient way of doing this (for me, at least) would be for you to implement the composition checks in the code yourself, once I've written the module code that does it. This *should* be very straightforward, requiring little extra time compared to making a document to send me. I will put together a short guide on how to do it. What would be useful for me now though is to have the information for one of the models (if you have it to hand) that I could use to test the code and make a demonstration of how to implement it. However, I'm also happy to implement them all, and a compiled document would be super helpful!!

**Comment by kaylai** [comment] 2020-05-27 14:54
Simon, this sounds amazing!!! I anxiously await implementation so I can see this masterpiece in action.

**Comment by gordon5m** [comment] 2020-05-27 15:13
I second this!

**Comment by simonwmatthews** [comment] 2020-05-27 16:01
I'm feeling the pressure now...

**Comment by kaylai** [comment] 2020-05-27 16:05
Are you feeling it in bars or MPa?

**Comment by simonwmatthews** [comment] 2020-05-27 16:07
If only I was feeling the pressure in a Bar...!

**Comment by kaylai** [comment] 2020-06-04 15:24
Circling back to this. This is somewhat separate from the check_calibration_range() method, since this get_calibration_range() would be informative. I'm thinking of coding it up as a universal informative method, alongside get_model_names(), under no class.

Let me know if anyone has better ideas on implementation.

**Comment by simonwmatthews** [comment] 2020-06-04 15:29
I was planning on building this into the calibration check structure, so that it needn't be defined twice in the same model. I.e., you generate the objects that define the calibration range, these are then used if the check_calibration_range() method is called, but would also be the basis for printing an output for a get_calibration_range() method. Will be starting work on this in the next few days, once I've caught up on admin, now the Goldschmidt deadline has passed...

**Comment by kaylai** [comment] 2020-06-04 20:06
@simonwmatthews Sounds good. I'll be patient and wait until you've taken more of a crack at the check_calibration_range()!

**Comment by simonwmatthews** [comment] 2020-06-11 09:39
get_calibration_range() methods now defined for every model, it will return a string description of the bounds. Happy to modify/extend! It would also be possible to use the new structure to define areas on plots where calculations are within the calibration range. Currently only defined for a single 'level', but we could easily extend this to having two 'levels': one for reported calibration ranges, and one for the ranges of experimental verification. I've only translated the existing checks, but it will be straightforward to add more complex checks- i.e. checking where a sample is in TAS space.

**Comment by PennyWieser** [comment] 2020-06-12 08:58
Hi Simon, I think its currently comparing the temp in the file with the limits, assuming the input temp is in K rather than C? It says ".... as 1163.4 K is not between 1473.2 and 1523.2 K" for shishkina, but the former is my input in C in the spreadsheet? I was at least assuming from the manuscript users input C in T?

**Comment by simonwmatthews** [comment] 2020-06-12 09:24
All of the non-MagmaSat methods use K. This is on my list of things to change. I guess the spreadsheet methods don't do the conversion, which won't be a problem once I've converted to degC.

**Comment by PennyWieser** [comment] 2020-06-12 09:26
So if I'm using
satPs_wtemps_IM = myfile.calculate_saturation_pressure(temperature="Temp", model='IaconoMarziano')

Is using the input T from my spreadsheet as if it were kelvin? If so this might explain a few of the small offsets i'm seeing. Or is it converting in the code already for the PSat calculation but not for the check calibration range?

**Comment by simonwmatthews** [comment] 2020-06-12 09:30
I guess so, but I don't know the details of how the spreadsheet code works. I would check this by following through the code and see if there's any point at which conversion happens before calling the calculate_saturation_pressure() class.

**Comment by PennyWieser** [comment] 2020-06-12 09:30
Also I'm wondering how people are going to use the errors we spit out for bulk calculation of PSats-It gets out of hand pretty quickly (partially because they are all erroring due to the temp offset) but even so, its doesn't' say which sample # is causing the error, so if you got 1 error out of 100 inputs, you wouldn't know which one. 
![image](https://user-images.githubusercontent.com/65668673/84488053-8e8f0c00-ac97-11ea-965c-bd4cc19d405e.png)
I don't know if there is any easy way to do this, but in the output spreadsheet, would it be possible to have an extra column like this so when people export, they can see what ranges were broken? Or maybe the full error message? 
![image](https://user-images.githubusercontent.com/65668673/84488147-ab2b4400-ac97-11ea-8b62-f286737ee005.png)

**Comment by simonwmatthews** [comment] 2020-06-12 09:31
Yes, this code needs updating for the new calibration check structure.

**Comment by PennyWieser** [comment] 2020-06-12 09:47
I guess for Shishkina bulk Psat calculations, the only place the T comes in is through the fugacity on line 1580, which says Temp is input in Kelvin. @kaylai @simonwmatthews Is there a plan before submission to make sure all the calculations are performing for a given input "temperature" that is either in celcius as the user inputs (and converted to kelvin for a specific calculation that requires Kelvin), or vice versa? Otherwise it's pretty confusing to someone who didn't write the code what each bit is doing with the input file. E.g. if state that "temperature" input is always Celcius, adapt
`		if 'temperature' in parameters.keys():
			temperature_results = {'Shishkina Model': (parameters['temperature']>1200+273.15) and (parameters['temperature']<1250+273.15),
									'Fugacity Model': self.fugacity_model.check_calibration_range(parameters)['temperature'],
									'Activity Model': self.activity_model.check_calibration_range(parameters)['temperature']}
			results['temperature'] = temperature_results`
To
`		if 'temperature' in parameters.keys():
			temperature_results = {'Shishkina Model': (parameters['temperature']>1200) and (parameters['temperature']<1250),
									'Fugacity Model': self.fugacity_model.check_calibration_range(parameters)['temperature'],
									'Activity Model': self.activity_model.check_calibration_range(parameters)['temperature']}
			results['temperature'] = temperature_results`

Etc.

**Comment by simonwmatthews** [comment] 2020-06-12 09:49
Yes, the methods will all take degC as input, it is on my list.

**Comment by PennyWieser** [comment] 2020-06-12 09:49
Great, sorry just wanted to clarify that it would be C!

**Comment by kaylai** [comment] 2020-06-12 16:41
> All of the non-MagmaSat methods use K. This is on my list of things to change. I guess the spreadsheet methods don't do the conversion, which won't be a problem once I've converted to degC.

Ahh, that's interesting. I thought all of the methods took in degrees C! I must have just TOTALLY glossed over that since the doc strings were added in later. In any event, if this needs to be changed, is it worth branching out as a new issue so that we can track it separately?

BTW MooreWater takes degrees C already.

**Comment by kaylai** [comment] 2020-06-12 16:42
> Also I'm wondering how people are going to use the errors we spit out for bulk calculation of PSats-It gets out of hand pretty quickly (partially because they are all erroring due to the temp offset) but even so, its doesn't' say which sample # is causing the error, so if you got 1 error out of 100 inputs, you wouldn't know which one.
> ![image](https://user-images.githubusercontent.com/65668673/84488053-8e8f0c00-ac97-11ea-965c-bd4cc19d405e.png)
> I don't know if there is any easy way to do this, but in the output spreadsheet, would it be possible to have an extra column like this so when people export, they can see what ranges were broken? Or maybe the full error message?
> ![image](https://user-images.githubusercontent.com/65668673/84488147-ab2b4400-ac97-11ea-8b62-f286737ee005.png)

Yes, that will be possible. I can add this functionality in. We should also be able to make the warning message report which sample is causing the warning.

**Closed** 2020-07-16 22:52 UTC
Labels: enhancement, question
