### ISSUE TITLE
Add compositional ranges to check_calibration_range() routines

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#56] opened 2020-05-26 19:51 UTC

**Comment by PennyWieser** [comment] 2020-06-02 18:04
I've added 2 1st drafts of some notebooks to a new folder "calibration"- the 1st, Calibration_plotting does standard plotting any user might want to assess calibration datasets - e.g. TAS diagram for all models, TAS for specific model, any given X-Y. It also plots things which are specific limitations of certain models. For example, it plots the full Dixon Pi for user samples vs. SiO2 so they can assess if the north arch SiO2 Pi calibration is suitable for their samples. It also shows how volatile calc does SiO2>49. Similary, i've made plots for FeO vs MgO and K2O vs Na2O for Iacono-Maziano which they specify as oxides they haven't constrained very well. 

The second notebook- Calibration_Datasets_Specific_Warnings -includes all the statements i've pulled out of the respective papers about model limitations, and specific errors. The way I was sort of seeing this working was each model returns a "use statement" which gives generic warnings (e.g. for dixon, we've used Pi vs SiO2 simplification), and then more specific user triggered warnings such as your pressure is out of range. These can all be reworded, but hopefully this is a good start of where authors have specifically warned against certain things

@simonwmatthews  I've left quite a few comments in red, we should discuss how to implement certain things that are out of range - E.g. if you see Iacono-Marziano, we should have a warning if FeO out of range, but the dataset has some anomalous values, so maybe return something like "only 1 sample in the dataset has FeO as high as your sample". Maybe we can set up a skype chat once you have some time to work out how to do this/what to do for each model?

**Comment by kaylai** [comment] 2020-06-04 15:20
Penny, this is great!

Can you please upload Dixon_1997_NorthArchData.xlsx to the Calibration folder?

**Comment by PennyWieser** [comment] 2020-06-04 16:15
Oops, knew i'd forget something. Should be there now!

You can see with this some of the issues we might have with #40  - some of the true "ranges" of the dataset aren't where the majority of points are - e.g., the P range of the Moore model is technically up to 6067 bars, but only 2 datapoints, and authors recommend 0-3000 bars.

 Similarly, Iacono-Marziano warn that most MgO is 6- 8 wt% so it poorly incorporates changes outside of this (which I have been found to be definitely true at Kilauea), but technically as there are some points in the dataset with MgO up to 10 wt%, so it wouldn't necessarily return an error. Similarly, they also warn about FeO - but there is 1 group of data with 0 wt% FeO, so would make it seem like you can go down to low FeO, while you can clearly see from the histograms I have put in the "specific warnings" notebook that the calibration dataset is not well distributed within these limits. This is sort of why I was favouring returning more generic messages, some of which are triggered by the data input, rather than printing out exact ranges that people can interpret wrongly due to 1 outlying point in the calibratoin dataset, and encouraging people to interrogate their datasets properly vs. the calibration ranges in the other notebooks. Some examples are in the "specific warnings" spreadsheet of sort of what I was thinking (but feel free to disagree!)

**Comment by PennyWieser** [comment] 2020-08-10 08:50
Hi @simonwmatthews and @kaylai, I'm trying to decide best way to do this. I think a reasonable definition of the calibration range is range of calibration dataset +-5%. The problem is, the error messages for the mixed models become quite convoluted as they combine all the errors from water and carbon models. Would it be better to have a separate set of error messages? E.g., For the mixed Liu model at the moment for something out of range in only a few major elements:

"/home/jovyan/ThermoEngine/Notebooks/Development/Final_Model_Tests_Agree/VESIcal.py:1714: RuntimeWarning: The pressure is outside the calibration range of the Liu et al. (2005) water model, as 5001.0 bar is not between 1.0 and 5000.0 bar. SiO2 is outside the calibration range of the Liu et al. (2005) water model, as 60.3 wt% is not between 71.0 and 82.0 wt%. Na2O is outside the calibration range of the Liu et al. (2005) water model, as 6.0 wt% is not between 3.2 and 4.9 wt%. K2O is outside the calibration range of the Liu et al. (2005) water model, as 6.0 wt% is not between 3.2 and 4.9 wt%. As the Liu et al. model incorperates no term for compositional dependence, users must take extreme care when extrapolating this model to compositions which differ significantly from the haplogranites and rhyolites in the calibration dataset. These calibration limits were selected based on the range of the calibration dataset +- 5%. These warnings are simply a guide; we suggest that users carefully compare their major element data to the calibration dataset to check for suitability The pressure is outside the calibration range of the Liu et al. (2005) Carbon model, as 5001.0 bar is not between 1.0 and 5000.0 bar. SiO2 is outside the calibration range of the Liu et al. (2005) Carbon model, as 60.3 wt% is not between 71.0 and 82.0 wt%. Na2O is outside the calibration range of the Liu et al. (2005) Carbon model, as 6.0 wt% is not between 3.2 and 4.9 wt%. K2O is outside the calibration range of the Liu et al. (2005) Carbon model, as 6.0 wt% is not between 3.2 and 4.9 wt%. As the Liu et al. model incorperates no term for compositional dependence, users must take extreme care when extrapolating this model to compositions which differ significantly from the haplogranites and rhyolites in the calibration dataset. These calibration limits were selected based on the range of the calibration dataset +- 5%. These warnings are simply a guide; we suggest that users carefully compare their major element data to the calibration dataset to check for suitability 
  w.warn(self.calib_check,RuntimeWarning)"

A related issue is dealing with P and T. E.g., The actual ranges of H2O and CO2 are (middle = press, RHS=temp)
![image](https://user-images.githubusercontent.com/65668673/89765679-b7444e00-daee-11ea-8ac4-83b78a042286.png)
but in their paper, Liu say overal model (H2O-CO2) for 700-1200C and 0-500 Mpa, so I guess the mixed model should have these, rather than the true ranges. At the moment I've put this range for carbon and water, but thats not really true, as CO2 isn't actually calibrated at low pressures.

**Comment by simonwmatthews** [comment] 2020-08-10 09:07
There is a 'hack' that would do this, probably easiest for me to demonstrate it by implementing an example. I'll do this for the Liu model later today.

**Comment by PennyWieser** [comment] 2020-08-10 09:17
If you let me know when you're going to start i'll send on the code I've done so far, I just am wondering generally how to deal with this, e.g., for just LiuWater do we want to use these calibration ranges or the author suggested range? E.g., for Moore, they are quite different (190-6067 bar calib range vs. 0-3000 bars author suggested). I'm tempted to go with the author suggested range (although the hack for simplified messages is still needed to stop duplicate messages for the mixed models).  I've also decided to simplify the table in the text to just show the author suggested with the true range as footnotes in the figure caption. Do you think this is best?
![image](https://user-images.githubusercontent.com/65668673/89767870-b3b2c600-daf2-11ea-9bfc-69149d156314.png)

**Comment by simonwmatthews** [comment] 2020-08-13 14:35
Implemented the single Liu (mixed model) warnings- can you check that they are doing what you wanted @PennyWieser ?
The extra code is:
`default_models['Liu'].models[1].set_calibration_ranges([])
_crs_to_update = default_models['Liu'].models[0].calibration_ranges
for _cr in _crs_to_update:
	_cr.model_name = 'Liu et al. (2005)'
default_models['Liu'].models[0].set_calibration_ranges(_crs_to_update)`

**Comment by kaylai** [comment] 2020-08-19 21:05
@PennyWieser perhaps it makes sense to add a "Note" column to that table, rather than putting the footnotes in. Either way, can you please add that the Allison model performs all calculations at 1200 °C regardless of user input temperature, and that the authors suggest that this should be applicable to melts between ~1100–1400 °C? When you have the new table, can you drop into the google doc please?

**Comment by PennyWieser** [comment] 2020-08-31 15:49
All compositional + PT checks I can think of are now implemented now simon has merged my file! :)

**Closed by PennyWieser** 2020-08-31 15:49 UTC
